name: 'Doxygenize'
description: 'Generate Doxygen code documentation and publish it to GitHub Pages'
inputs:
  actor:
    description: 'GitHub Actor'
    required: true
  token:
    description: 'GitHub Token'
    required: true
  respository:
    description: 'GitHub Repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.actor }}
  - ${{ inputs.token }}
  - ${{ inputs.repository }}