name: 'Doxygenize'
description: 'Generate Doxygen code documentation and publish it to GitHub Pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ github.actor }}
  - ${{ github.token }}
  - ${{ github.repository }}